language: python
python:
  - 2.7

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6
  - nvm use 6
install:
  - pip install -r requirements.txt
  - npm install
  - gem install coveralls-lcov

before_script:
  - cp config/options/client.json.template config/options/client.json
  - cp config/options/server.json.template config/options/server.json
  - cp config/secrets/client.json.template config/secrets/client.json
  - cp config/secrets/server.json.template config/secrets/server.json
script:
  - npm run lint
  - npm run build
  - npm run coveralls
